
name: Deploy Development of CLC

'on':
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  #this workfloe has only one job
  deploy_to_dev_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
      - name: create .env
        run: |
          cd functions
          mv .env.dev .env
      - name: Install dependencies
        run: |
          cd functions
          yarn install
      - name: Deploy to dev site
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project devenvclc
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
