
name: Deploy Development of CLC

# Controls when the workflow will run
'on':
  #triggers the workflow whenever a push is made to the main branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  #this workfloe has only one job
  deploy_to_dev_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
      # this install the dependencies specified in your package.json file into the current workflow
      - name: Install dependencies
        # navigates to your functions folder and install the dependencies
        run: |
          cd functions
          yarn install
        # If your firebase cloud functions project uses firebase-admin 
        # you need to create a config file used to initialize your project
        # the below task creates a config.json file in your functions directory
      - name: Deploy to dev site
        uses: w9jds/firebase-action@master
        with:
          args: use dev && deploy --only functions
        env:
          FIREBASE_TOKEN: 1//0cl4PB84ArIB7CgYIARAAGAwSNwF-L9Irtq5CTk_m4VcGqk2T4ILl78mrS3BH80i9QUC-XOXzh_Ecf_X0wzZVDvqjxNfr3gx3cbg
